sudo: required

language: java
#jdk:
 # - oraclejdk8

matrix:
 allow_failures:
  - os: osx
 include:
  - os: linux
    sudo: required
    jdk: oraclejdk8
    services: docker
  - os: osx
    osx_image: xcode8.3
  
#services:
 # - docker

env:
 global:	
  - mssql_jdbc_test_connection_properties='jdbc:sqlserver://localhost:1433;databaseName=master;username=sa;password=<YourStrong!Passw0rd>;'
  - mssql_jdbc_logging='true'
  # Enabling logging with console / file handler for JUnit Test Framework. 
  #- mssql_jdbc_logging_handler='console'|'file'

install: 
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -Pbuild41
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -Pbuild42

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker pull microsoft/mssql-server-linux; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker run -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=<YourStrong!Passw0rd>' -p 1433:1433 -d microsoft/mssql-server-linux; fi

script: 
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker ps -a; fi
  
##Test for JDBC Specification 41 & 42 and submit coverage report.
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then mvn test -B -Pbuild41 jacoco:report && bash <(curl -s https://codecov.io/bash) -cF JDBC41; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then mvn test -B -Pbuild42 jacoco:report && bash <(curl -s https://codecov.io/bash) -cF JDBC42; fi

#after_success:
# instead of after success we are using && operator for conditional submitting coverage report.
#  - bash <(curl -s https://codecov.io/bash)
